Website = "https://github.com/SMerrony/DasherG"

[Details]
Icon = "DGlogoOrange.png"
Name = "DasherG"
ID = "fr.merrony.dasherg"
Version = "v0.17.0"
Build = 1

[LinuxAndBSD]
GenericName = "Terminal Emulator"
Categories = ["Network", "TerminalEmulator"]
Comment = "Data General DASHER terminal emulator"
Keywords = ["terminal", "emulator"]
